image: debian:buster-20200422-slim

before_script:
  - DEBIAN_FRONTEND=noninteractive apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends git git-lfs hugo make curl awscli openssh-client

deploy:
  stage: deploy
  script:
    - git submodule init
    - git submodule update --remote
    - git lfs pull
    - make s3_upload

