version: 2

jobs:
  build:
    docker:
      - image: debian:buster-slim

    steps:
      - checkout

      - run:
          name: Install Packages
          command: |
            DEBIAN_FRONTEND=noninteractive sudo apt-get install --yes --no-install-recommends git git-lfs hugo make curl awscli

      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
            git lfs pull

      - restore_cache:
          keys:
            - project-cache

      - run:
          name: Publish Locally
          command: |
            unset AWS_ACCESS_KEY_ID
            unset AWS_SECRET_ACCESS_KEY
            make publish

      - run:
          name: Upload locally Published Results
          command: |
            make just_s3_upload

