version: 2

jobs:
  build:
    docker:
      - image: debian:buster-slim

    steps:

      - run:
          name: Install Packages
          command: |-
            DEBIAN_FRONTEND=noninteractive apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends git git-lfs hugo make curl awscli

      - checkout

      - run:
          name: Pull with Submodules and LFS Files
          command: |-
            git submodule init
            git submodule update --remote
            git lfs pull

      - run:
          name: Publish
          command: |-
            make just_s3_upload

